# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_tips_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tips',
            options={'verbose_name': 'Tips'},
        ),
        migrations.AddField(
            model_name='tips',
            name='imgdesc',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
