# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20161007_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tips',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
